type DevMode = "PRODUCTION" | "DEVELOPMENT";

const DEV_MODE: DevMode = "PRODUCTION";

const PAYLOAD_LIMIT_MAX_KB_SIZE = 1024;

const CONFIG_INNER = {
  PRODUCT_NAME: "CodeBud",
  MAX_IDENTICAL_CONSOLE_WARNINGS_IN_A_ROW: 3,
  DOMAIN: "unitap.online",
  MAIN_URL: "https://unitap.online",
  BASE_URL: 'https://unitap.online/api',
  DEV: {
    "PRODUCTION": false,
    "DEVELOPMENT": true
  },
  MAIN_SOCKET_ADDRESS: {
    "PRODUCTION": "https://unitap.online",
    "DEVELOPMENT": "http://192.168.0.14:3000"
  },
  SOCKET_PATH: {
    "PRODUCTION": "/connect/socket.io",
    "DEVELOPMENT": ""
  },
  SOCKET_RECONNECTION_DELAY: 5e3,
  NETWORK_INTERCEPTOR: {
    FILTER_INNER_REQUESTS: {
      "PRODUCTION": true,
      "DEVELOPMENT": true
    }
  },
  PAYLOAD_LIMITS: {
    MAX_KB_SIZE: PAYLOAD_LIMIT_MAX_KB_SIZE,
    MAX_BYTE_SIZE: 1024 * PAYLOAD_LIMIT_MAX_KB_SIZE,
    MIN_STRING_LENGTH_POSSIBLE_OVERLOAD: 1024 * PAYLOAD_LIMIT_MAX_KB_SIZE / 4 // MAX_BYTE_SIZE / 4 (4 is max possible byteSize of UTF char)
  }
};

export const CONFIG = {
  ...CONFIG_INNER,
  DEV: CONFIG_INNER.DEV[DEV_MODE],
  MAIN_SOCKET_ADDRESS: CONFIG_INNER.MAIN_SOCKET_ADDRESS[DEV_MODE],
  SOCKET_PATH: CONFIG_INNER.SOCKET_PATH[DEV_MODE],
  NETWORK_INTERCEPTOR: {...CONFIG_INNER.NETWORK_INTERCEPTOR, FILTER_INNER_REQUESTS: CONFIG_INNER.NETWORK_INTERCEPTOR.FILTER_INNER_REQUESTS[DEV_MODE]}
};